deployments:
  deploymentGating:
    enabled: true 
    retry: 20  
    sleep: 10 
    environments: 
    - Development
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS81NzU1ZWVmYS1lMTI5LTExZWUtYjIzMi0xMjhiNDI4MTk0MjQ=
