deployments:
  deploymentGating:
    enabled: true 
    retry: 200  
    sleep: 10 
    environments: 
    - Development
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS80NjFkM2IyMC0yZWRiLTExZWYtYWEzMi0wYWJlM2Y0YTY2MDE=
